version: '3.8'
services:
  app:
    container_name: graphql_app
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
